package ib

const (
	mOrderTypeNone                    = ""
	mOrderTypeMarket                  = "MKT"
	mOrderTypeLimit                   = "LMT"
	mOrderTypeStop                    = "STP"
	mOrderTypeStopLimit               = "STP LMT"
	mOrderTypeRelative                = "REL"
	mOrderTypeTrail                   = "TRAIL"
	mOrderTypeBoxTop                  = "BOX TOP"
	mOrderTypeFixPegged               = "FIX PEGGED"
	mOrderTypeLimitIfTouched          = "LIT"
	mOrderTypeLimitPlusMarket         = "LMT + MKT"
	mOrderTypeLimitOnClose            = "LOC"
	mOrderTypeMarketIfTouched         = "MIT"
	mOrderTypeMarketWithProtection    = "MKT PRT"
	mOrderTypeMarketOnClose           = "MOC"
	mOrderTypeMarketToLimit           = "MTL"
	mOrderTypePassiveRelative         = "PASSV REL"
	mOrderTypePeggedToBenchmark       = "PEG BENCH"
	mOrderTypePeggedToMidpoint        = "PEG MID"
	mOrderTypePeggedToMarket          = "PEG MKT"
	mOrderTypePeggedToPrimary         = "PEG PRIM"
	mOrderTypePeggedToStock           = "PEG STK"
	mOrderTypeRelativePlusLimit       = "REL + LMT"
	mOrderTypeRelativePlusMarket      = "REL + MKT"
	mOrderTypeSnapMidpoint            = "SNAP MID"
	mOrderTypeSnapMarket              = "SNAP MKT"
	mOrderTypeSnapPrimary             = "SNAP PRIM"
	mOrderTypeStopWithProtection      = "STP PRT"
	mOrderTypeTrailLimit              = "TRAIL LIMIT"
	mOrderTypeTrailLimitIfTouched     = "TRAIL LIT"
	mOrderTypeTrailLimitPlusMarket    = "TRAIL LMT + MKT"
	mOrderTypeTrailMarketIfTouched    = "TRAIL MIT"
	mOrderTypeTrailRelativePlusMarket = "TRAIL REL + MKT"
	mOrderTypeVolume                  = "VOL"
	mOrderTypeVwap                    = "VWAP"
	mOrderTypeQuote                   = "QUOTE"
	mOrderTypePeggedPrimaryVolume     = "PPV"
	mOrderTypePeggedMidpointVol       = "PDV"
	mOrderTypePeggedMarketVol         = "PMV"
	mOrderTypePeggedSrfVol            = "PSV"
)
